# Generated by Django 4.2 on 2023-11-17 01:51

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default=categories.models.Category.default_directory_path, null=True, upload_to=categories.models.Category.directory_path)),
            ],
        ),
    ]
