# Generated by Django 4.2 on 2023-10-17 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('inventory', 'Inventory Order'), ('product', 'Product Order')], max_length=128)),
                ('status', models.CharField(choices=[('created', 'New'), ('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('aborted', 'Aborted'), ('stale', 'Stale')], default='created', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(max_length=20, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('total_amount', models.PositiveIntegerField(editable=False)),
                ('shipping_method', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='products.productitem')),
            ],
        ),
    ]
