# Generated by Django 4.2 on 2023-11-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('inventory', 'Inventory Order'), ('product', 'Product Order')], editable=False, max_length=128)),
                ('status', models.CharField(choices=[('created', 'New'), ('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('aborted', 'Aborted'), ('stale', 'Stale')], default='created', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(max_length=20, null=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('unit_price', models.PositiveIntegerField(null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.PositiveIntegerField(null=True)),
                ('shipping_method', models.CharField(choices=[('default', 'Default')], default='default', max_length=20)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
