# Generated by Django 4.2 on 2023-10-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='notes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
